config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    return if user.nil?

    if user.admin?
      can :access, :rails_admin   # grant access to rails_admin
      can :dashboard              # grant access to the dashboard
      can :manage, :all
    else
      can [:index, :show, :create, :new], Post
      can [:update, :edit, :destroy], Post do |post|
        post.user_id == user.id
      end

      can [:index, :create, :new], Comment
      can [:update, :edit, :destroy], Comment do |comment|
        comment.user_id == user.id
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  belongs_to :parent,   class_name: 'Comment', foreign_key: 'parent_id'

  has_many   :children, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy

  validates :user, presence: true
  validates :post, presence: true
  validates :body, presence: true

  default_scope { order(:created_at)}

  self.per_page = 5
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :commenters, through: :comments, source: :user

  validates :user,  presence: true
  validates :title, presence: true
  validates :body,  presence: true

  default_scope { order(created_at: :desc) }

  self.per_page = 5

  def full_title
    "##{id} #{title}"
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :users, through: :assignments

  validates :name, presence: true, uniqueness: true, allow_blank: false
end

app/models/user.rb
class User < ApplicationRecord
  has_many :assignments, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :roles, through: :assignments
  has_many :commented_posts, through: :comments, source: :post

  validates :first_name, presence: true
  validates :last_name,  presence: true

  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable,
         :confirmable

  before_create :set_default_role

  def admin?
    role?(:admin)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  protected

  def role?(role)
    roles.any? { |r| r.name.underscore.to_sym == role }
  end

  def set_default_role
    roles << Role.find_by(name: 'user')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, error: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name, :avatar ])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar, :remove_avatar])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource only: [:edit, :update, :destroy]

  def create
    @post = Post.find(params[:post_id])

    @comment = Comment.new(create_params)

    if (create_params[:parent_id])
      @parent = Comment.find(create_params[:parent_id])
      @comment.parent = @parent
    end

    @comment.user = current_user
    @comment.post = @post

    authorize! :create, @comment

    if @comment.save
      flash[:success] = 'Comment created successfully.'
    else
      flash[:error] = @comment.errors.full_messages.to_sentence
    end

    redirect_to(post_url(params[:post_id]))
  end

  def edit
  end

  def update
    if @comment.update_attributes(update_params)
      flash[:success] = 'Comment updated successfully.'
      redirect_to post_url(@comment.post_id)
    else
      flash.now[:error] = @comment.errors.full_messages.to_sentence
      render action: :edit
    end
  end

  def destroy
    @post = Post.joins(:comments).find(params[:post_id])

    if @comment.destroy
      @comments = @post.comments

      respond_to do |f|
        f.html do
           flash[:success] = 'Comment deleted successfully.'
           redirect_to post_url(@post)
        end
        f.xml  { head :ok }
        f.js do
          flash.now[:success] = 'Comment deleted successfully.'
          render 'comments.js.erb'
        end
      end
    else
      @comments = @post.comments

      respond_to do |f|
        f.html do
           flash[:error] = @comment.errors.full_messages.to_sentence
           redirect_to post_url(@post)
        end
        f.xml  { head :ok }
        f.js do
          flash.now[:error] = @comment.errors.full_messages.to_sentence
          render 'comments.js.erb'
        end
      end
    end
  end

  protected

  def create_params
    params.require(:comment).permit(:body, :parent_id)
  end

  def update_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to posts_url if user_signed_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource only: [:new, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def new
  end

  def create
    @post = Post.new(create_params)
    @post.user = current_user

    authorize! :create, @post

    if @post.save
      flash[:success] = 'Post created successfully.'
      redirect_to posts_url
    else
      flash.now[:error] = @post.errors.full_messages.to_sentence
      render :new
    end
  end

  def show
    @post = Post.includes(:user, comments: [:user, :children, :parent]).find(params[:id])

    authorize! :show, @post
  end

  def edit
  end

  def update
    if @post.update_attributes(update_params)
      flash[:success] = 'Post updated successfully.'
      redirect_to post_url(@post)
    else
      flash.now[:error] = @post.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @posts = Post.paginate(page: params[:page])

    if @post.destroy
      respond_to do |f|
        f.html do
          flash[:success] = 'Post deleted successfully.'
          redirect_to(posts_url)
        end
        f.xml  { head :ok }
        f.js do
          flash.now[:success] = 'Post deleted successfully.'
          render 'posts.js.erb'
        end
      end
    else
      respond_to do |f|
        f.html do
          flash[:error] = @post.errors.full_messages.to_sentence
          redirect_to(posts_url)
        end
        f.xml  { head :ok }
        f.js do
          flash.now[:error] = @post.errors.full_messages.to_sentence
          render 'posts.js.erb'
        end
      end

    end
  end

  protected

  def create_params
    params.require(:post).permit(:title, :body, :post_id)
  end

  def update_params
    params.require(:post).permit(:title, :body, :post_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    if (page_title.present?)
      "Blog | #{page_title}"
    else
      'Blog'
    end
  end

  def truncate_text(text, length = 25)
    return text if text.length < length

    "#{text[0..length]}..."
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = []

    resource.errors.full_messages.each do |m|
      messages << content_tag(:div, class: 'flash__message') do
        content_tag(:span, 'error', class: 'flash__message__type') + 
        content_tag(:p, m, class: 'flash__message__text')
      end
    end

    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
      #{messages.join}
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment<% if parent %> comment--bordered<% end %>" <% if parent %><%= "data-parent-id=\"#{parent.id}\"" %><% end %>>
  <div class="comment__body">
    <p class="comment__body__text">
      <%= comment.body %>
    </p>
  </div>

  <div class="comment__footer">
    <% if can? :destroy, comment %>
      <%= link_to '', post_comment_url(comment.post, comment), method: :delete, remote: true, class: 'icon icon--trash icon--link', data: { confirm: 'Are you sure?' } %>
    <% end %>
    <% if can? :edit, comment %>
      <%= link_to '', edit_post_comment_url(comment.post, comment), class: 'icon icon--pencil icon--link' %>
    <% end %>
    <span class="icon icon--link comment__footer__reply-button">Reply</span>
    <% if comment.children.any? %>
      <span class="icon icon--comments">
        <%= comment.children.length %>
      </span>
    <% end %>
    <%= image_tag comment.user.avatar.thumb.url, class: 'comment__footer__image', alt: comment.user.full_name %>
    <span class="comment__footer__time"><%= comment.user.full_name %> (<%= comment.created_at %>)</span>
  </div>

  <%= render partial: 'comments/comment_create_form', locals: { parent: comment, post_id: comment.post.id, is_reply: true } %>

  <div class="comment-children">
    <%= render partial: 'comments/comments', locals: { comments: comment.children, parent: comment } %>
  </div>
</div>

app/views/comments/_comment_create_form.html.erb
<div class="comment-form-wrapper comment-form-wrapper--hidden">
  <form class="comment-form" action="<%= post_comments_url(post_id) %>" accept-charset="UTF-8" method="post">
    <div class="comment-form__header">
      <h3 class="comment-form__header__title">
        <% if parent %>
          Reply to: <%= parent.user.full_name %> "<%= parent.body[0..25] %>..."
        <% else %>
          New comment
        <% end %>
      </h3>
      <button class="comment-form__header__close-button"></button>
    </div>

    <div class="comment-form__body">
      <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
      <% if parent %>
        <input type="hidden" name="comment[parent_id]" value="<%= parent.id %>"/>
      <% end %>
      <div class="form-field">
        <textarea name="comment[body]" id="comment_body" class="form-field__text-area" rows="5"></textarea>
      </div>
      <div class="form-field">
        <input type="submit" name="commit" value="Submit" class="button button--green" data-disable-with="Submit"/>
      </div>
    </div>
  </form>
</div>

app/views/comments/_comment_edit_form.html.erb
<%= form_for(comment, url: post_comment_url(comment), html: { method: :patch, class: 'comment-form' }) do |f| %>
  <div class="comment-form__header">
    <h3 class="comment-form__header__title">Edit comment</h3>
  </div>
  <div class="comment-form__body">
    <% if parent %>
      <input type="hidden" name="comment[parent_id]" value="<%= parent.id %>"/>
    <% end %>
    <div class="form-field">
      <textarea name="comment[body]" id="comment_body" class="form-field__text-area" rows="5"><%= comment.body %></textarea>
    </div>
    <div class="form-field">
      <input type="submit" name="commit" value="Submit" class="button button--green" data-disable-with="Submit"/>
    </div>
  </div>
  <div class="comment__footer">
    <%= image_tag comment.user.avatar.thumb.url, class: 'comment__footer__image', alt: comment.user.full_name %>
    <span class="comment__footer__time"><%= comment.user.full_name %> (<%= comment.created_at %>)</span>
  </div>
<% end %>

app/views/comments/_comments.html.erb
<div class="comments">
  <% comments.each do |comment| %>
    <%= render partial: 'comments/comment', locals: { comment: comment, parent: comment.parent} %>
  <% end %>
</div>

app/views/comments/comments.js.erb
$(document).ready(function() {
  $('.comments').replaceWith('<%=j render partial: 'comments', locals: { comments: @comments } %>');

  <% if flash[:success] %>
    toastr.success('<%= flash[:success] %>', 'Success');
  <% end %>

  <% if flash[:error] %>
    toastr.error('<%= flash[:error] %>', 'Error');
  <% end %>

  initCommentButtons();
});

app/views/comments/edit.html.erb
<% provide :page_title, 'Edit comment' %>

<%= render partial: 'comment_edit_form', locals: { comment: @comment, post_id: @comment.post_id, parent: @comment.parent } %>

app/views/home/index.html.erb
<div class="welcome-box">
  <div class="welcome-box__header">
    <h1 class="welcome-box__header__text">Example blog</h1>
  </div>
  <div class="welcome-box__body">
    <p class="welcome-box__body__text">Welcome to the blog!</p>
    <%= link_to new_user_session_path, class:'button button--teal' do %>
      Sign in
    <% end %>
    <%= link_to new_user_registration_path, class:'button button--green' do %>
      Sign up
    <% end %>
  </div>
</div>

app/views/layouts/_flash.html.erb
<div class="flash">
  <% flash.each do |key, value| %>
    <div class="flash__message">
      <span class="flash__message__type"><%= key %></span>
      <p class="flash__message__text"><%= value %></p>
    </div>
  <% end %>

  <% if devise_controller? %>
    <%= devise_error_messages! %>
  <% end %>
</div>

app/views/layouts/_sidenav.html.erb
<nav class="sidenav sidenav--hidden">
  <% if user_signed_in? %>
    <div class="sidenav__header">
      <%= image_tag current_user.avatar.thumb.url, class: 'sidenav__header__image', alt: current_user.full_name %>
      <span class="sidenav__header__text"><%= current_user.full_name %></span>
    </div>
  <% end %>
  <ul class="sidenav__upper">
    <% if user_signed_in? %>
      <li class="sidenav__upper__item">
        <%= link_to 'Feed', posts_url, class: 'sidenav__upper__item__link' %>
      </li>
      <li class="sidenav__upper__item">
        <%= link_to 'New post', new_post_url, class: 'sidenav__upper__item__link' %>
      </li>
      <% if current_user.admin? %>
        <li class="sidenav__upper__item">
          <%= link_to 'Admin dashboard', rails_admin_url, class: 'sidenav__upper__item__link' %>
        </li>
      <% end %>
      <li class="sidenav__upper__item">
        <%= link_to 'Edit profile', edit_user_registration_url, class: 'sidenav__upper__item__link' %>
      </li>
      <li class="sidenav__upper__item">
        <%= link_to 'Sign out', destroy_user_session_url, method: :delete, class: 'sidenav__upper__item__link' %>
      </li>
    <% else %>
      <li class="sidenav__upper__item">
        <%= link_to 'Blog', root_url, class: 'sidenav__upper__item__link' %>
      </li>
      <li class="sidenav__upper__item">
        <%= link_to 'Sign in', new_user_session_url, class: 'sidenav__upper__item__link' %>
      </li>
    <% end %>
</nav>

<div class="sidenav-trigger">
  <button class="sidenav-trigger__button"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= render partial: 'layouts/flash', locals: { flash: flash } %>
    <%= render partial: 'layouts/sidenav' %>

    <main class="main-container">
      <h2 class="main-container__title"><%= yield(:page_heading) %></h2>
      <%= yield %>
    </main>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post" data-id="<%= post.id %>">
  <div class="post__header">
    <h3 class="post__header__title">
      <span class="post__header__title__number">#<%= post.id %></span>
      <%= post.title %>
    </h3>
  </div>

  <div class="post__body">
    <p class="post__body__text"><%= post.body %></p>
  </div>

  <div class="post__footer">
    <% if can? :destroy, post %>
      <%= link_to '', post_url(post), method: :delete, remote: async_delete, class: 'icon icon--trash icon--link', data: { confirm: 'Are you sure?' } %>
    <% end %>
    <% if can? :edit, post %>
      <%= link_to '', edit_post_url(post), class: 'icon icon--pencil icon--link' %>
    <% end %>
    <% if action_name == 'show' %>
      <span class="icon icon--link post__footer__comment-button">Comment</span>
    <% end %>
    <% if has_link %>
      <%= link_to(post_url(post.id), class: 'icon icon--comments icon--link') do %>
        <%= post.comments.count(:id) %>
      <% end %>
    <% else %>
      <span class="icon icon--comments">
        <%= post.comments.length %>
      </span>
    <% end %>    
    <%= image_tag post.user.avatar.thumb.url, class: 'post__footer__image', alt: post.user.full_name %>
    <span class="post__footer__time">
      <%= post.user.full_name %> (<%= post.created_at %>)
    </span>
  </div>
</div>

app/views/posts/_post_create_form.html.erb
<%= form_for(:post, url: posts_url, html: { method: :post, class: 'post-form' }) do |f| %>
  <div class="post-form__header">
    <h2 class="post-form__header__title">Write a post</h2>
  </div>
  <div class="post-form__body">
    <div class="form-field">
      <%= f.label :title, class: 'form-field__label' %>
      <%= f.text_field :title, autofocus: true, class: 'form-field__text-input' %>
    </div>
    <div class="form-field">
      <%= f.text_area :body, class: 'form-field__text-area', rows: 5 %>
    </div>
    <div class="form-field">
      <%= f.submit "Submit", class: 'button button--green' %>
    </div>
  </div>
<% end %>

app/views/posts/_post_edit_form.html.erb
<%= form_for(post, url: post_url(post), html: { method: :patch, class: 'post-form' }) do |f| %>
  <div class="post-form__header">
    <h2 class="post-form__header__title">Edit post</h2>
  </div>
  <div class="post-form__body">
    <div class="form-field">
      <%= f.label :title, class: 'form-field__label' %>
      <%= f.text_field :title, autofocus: true, class: 'form-field__text-input' %>
    </div>
    <div class="form-field">
      <%= f.text_area :body, class: 'form-field__text-area', rows: 5 %>
    </div>
    <div class="form-field">
      <%= f.submit "Submit", class: 'button button--green' %>
    </div>
  </div>

  <div class="post-form__footer">
    <%= image_tag post.user.avatar.thumb.url, class: 'post-form__footer__image', alt: post.user.full_name %>
    <span class="post-form__footer__time">
      <%= post.user.full_name %> (<%= post.created_at %>)
    </span>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div class="posts">
  <% if posts.any? %>
    <% posts.each do |post| %>
      <%= render partial: 'post', locals: { post: post, has_link: true, async_delete: true } %>
    <% end %>

    <%= will_paginate posts %>
  <% else %>
    <span class="posts__empty">No posts yet :(</span>
  <% end %>
</div>

app/views/posts/edit.html.erb
<% provide :page_title, "Edit post ##{@post.id}" %>

<%= render partial: 'post_edit_form', locals: { post: @post } %>

app/views/posts/index.html.erb
<% provide :page_title,   'Feed' %>
<% provide :page_heading, 'Feed' %>

<%= render partial: 'posts', locals: { posts: @posts } %>

app/views/posts/new.html.erb
<% provide :page_title, 'New post' %>

<%= render partial: 'post_create_form' %>

app/views/posts/posts.js.erb
$(document).ready(function() {
  $('.posts').replaceWith('<%=j render partial: 'posts', locals: { posts: @posts } %>');

  <% if flash[:success] %>
    toastr.success('<%= flash[:success] %>', 'Success');
  <% end %>
  
  <% if flash[:error] %>
    toastr.erorr('<%= flash[:error] %>', 'Error');
  <% end %>
});

app/views/posts/show.html.erb
<% provide :page_title,   @post.title %>
<% provide :page_heading, @post.title %>

<%= render partial: 'post', locals: { post: @post, has_link: false, async_delete: false, truncate_text: false } %>

<%= render partial: 'comments/comment_create_form', locals: { post_id: @post.id, parent: nil, is_reply: false } %>

<%= render partial: 'comments/comments', locals: { comments: @post.comments.where(parent_id: nil).paginate(page: params[:page]) } %>